/* WATCHDOG.CTRL */
pub const WATCHDOG_CTRL_TRIGGER_BIT: u32 = 1 << 31;
pub const WATCHDOG_CTRL_ENABLE_BIT: u32 = 1 << 30;
pub const WATCHDOG_CTRL_PAUSE_DBG1_BIT: u32 = 1 << 26;
pub const WATCHDOG_CTRL_PAUSE_DBG0_BIT: u32 = 1 << 25;
pub const WATCHDOG_CTRL_PAUSE_JTAG_BIT: u32 = 1 << 24;
pub const WATCHDOG_CTRL_TIME_SHIFT: usize = 0;
pub const WATCHDOG_CTRL_TIME_BITS: u32 = 0xFF_FFFF;

/* WATCHDOG.LOAD */
pub const WATCHDOG_LOAD_BITS: u32 = 0xFF_FFFF;

/* WATCHDOG.REASON */
pub const WATCHDOG_REASON_FORCE_BIT: u32 = 1 << 1;
pub const WATCHDOG_REASON_TIMER_BIT: u32 = 1 << 0;

/* WATCHDOG.SCRATCHX */
pub const WATCHDOG_SCRATCH4_MAGIC: u32 = 0xB007C0D3;

/* WATCHDOG.TICK */
pub const WATCHDOG_TICK_COUNT_SHIFT: usize = 11;
pub const WATCHDOG_TICK_COUNT_BITS: u32 = 0x1FF;
pub const WATCHDOG_TICK_RUNNING_BIT: u32 = 1 << 10;
pub const WATCHDOG_TICK_ENABLE_BIT: u32 = 1 << 9;
pub const WATCHDOG_TICK_CYCLES_BITS: u32 = 0x1FF;