[package]
name = "simple"
version = "0.0.1"
authors = ["Chris"]
edition = "2021"
description = "Simple pi pico baremetal experiment"

[dependencies]

[profile.dev]
strip = "none"
panic = "abort"

[profile.release]
panic = "abort"
strip = "symbols"
#opt-level = "s"
lto = true
